document.getElementById('fileInput').addEventListener('change', function(event) {
    const file = event.target.files[0];

    // Check if the file is an HTML file
    if (file.type !== 'text/html') {
        document.getElementById('results').innerHTML = `<p style="color: red;">Please upload a valid HTML file.</p>`;
        return;
    }

    const reader = new FileReader();

    reader.onload = function(e) {
        const parser = new DOMParser();
        const doc = parser.parseFromString(e.target.result, 'text/html');

        // Detect new Facebook format: look for "Generated by"
        let userNameElement = doc.querySelector('div._aoaa');
        let userName = 'User';

        // Handle old and new formats
        if (userNameElement && userNameElement.textContent.includes('Generated by')) {
            userName = userNameElement.textContent.split('by')[1].split('on')[0].trim();
        } else {
            let userNameOldElement = doc.querySelector('span._a7cv > a._a7cw._a7cy');
            userName = userNameOldElement ? userNameOldElement.textContent.trim() : 'User';
        }

        // Extract names
        let names = Array.from(doc.querySelectorAll('div._a6-i')).map(el => el.textContent.trim());

        if (names.length === 0) {
            document.getElementById('results').innerHTML = `<p style="color: red;">No names found in the uploaded HTML file.</p>`;
            return;
        }

        processNameData(userName, names);
    };

    reader.readAsText(file);
});
