export function handleFileUpload(file, processResultsCallback) {
    const reader = new FileReader();
    
    reader.onload = function(e) {
        const parser = new DOMParser();
        const doc = parser.parseFromString(e.target.result, 'text/html');

        // Detect new Facebook format: look for the "Generated by" phrase
        let userNameElement = doc.querySelector('div._aoaa');
        let userName = 'User'; // Default value

        // Check if it is the new format or the old one
        if (userNameElement && userNameElement.textContent.includes('Generated by')) {
            // New format handling
            userName = userNameElement.textContent.split('by')[1].split('on')[0].trim();
        } else {
            // Old format fallback
            let userNameOldElement = doc.querySelector('span._a7cv > a._a7cw._a7cy');
            userName = userNameOldElement ? userNameOldElement.textContent.trim() : 'User';
        }

        // Extract names from div with class _a6-i
        let names = Array.from(doc.querySelectorAll('div._a6-i')).map(el => el.textContent.trim());

        if (names.length === 0) {
            document.getElementById('results').innerHTML = `<p style="color: red;">No names found in the uploaded HTML file. Please ensure you are uploading the correct Facebook friend list HTML file.</p>`;
            return;
        }

        // Call the callback to process the results
        processResultsCallback(userName, names);
    };

    reader.readAsText(file);
}
